### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by adbh94** [kexinrong/NetworkSimulator#1]
Router:
BF, routing table, links hosts

Packet:
src, dest, size, type, timestamp

Host:
flow[], address

Link:
buffer, capacity

Flow:
congestion control

*event queue

**Comment by kexinrong** [comment]
Questions:
1. Difference between process based VS discrete event based (how to collect data etc.)
2. Does broadcasting packet take link capacity
3. Where to put congestion control algorithms

TODO:
1. simulation model decision
2. division of labor and timeline
3. presentation
*4. API
