### ISSUE TITLE
Globally unique id

### ISSUE THREAD

**Issue by kexinrong** [kexinrong/NetworkSimulator#15]
We need a globally unique id for each host/router so that link knows which devices it connects to. In addition, I think that we should unify the interface for get id, aka. flow.get_id(), router.get_id(), host.get_id() instead of host.get_host_id(), flow.get_flow_id().

**Comment by adbh94** [comment]
Updated host's interface by changing get_host_id() to get_id(). I think it is worthwhile to keep the get_flow_id() method for packets since changing that to get_id() may lead to confusion.

**Comment by aman-agarwal** [comment]
I think we should either have a unique ID for each object and have method get_id (as Kexin suggested), or have IDs from 1 to number of hosts for hosts, and similarly for flows, links and routers, and use method get_host_id etc.
