### ISSUE TITLE
Reporting for flows

### ISSUE THREAD

**Issue by aman-agarwal** [kexinrong/NetworkSimulator#19]
Should the environment call report() on a sending flow only after its start time?

**Comment by aman-agarwal** [comment]
This needs to be resolved. Right now env is calling report on a flow without any checks. Either the env must check that the flow has started/just ended, or the flow can return 0 for send/receive rates as well as RTT_delay.

**Comment by sdhpzhtk** [comment]
The flow should return back 0 for all stats.

郑韬堃 Taokun (Xander) Zheng

Email: tzheng@caltech.edu
Mobile: 1-626-354-2788

Address:
California Institute of Technology
MSC 1076, Pasadena, CA 91126
