### ISSUE TITLE
Router Design

### ISSUE THREAD

**Issue by adbh94** [kexinrong/NetworkSimulator#24]
Let's agree on a routing design before implementing it. I'd like to do dynamic routing without a statically initialized routing table. Here's one way we could do it.

Dynamic routing will use the Bellman-Ford algorithm with distance vectors, taking place every 5s. Link weights will be the propagation time of the RoutingUpdatePackets, which can be found without querying links. Based on this metric, the first distance estimate to a device must be the shortest since it reached the router first.

At the start of the simulation, all the routers will begin broadcasting their distance estimates. Hosts that receive a RoutingUpdatePacket will reply to alert the router that they are a host. Routers will mark the links corresponding to the hosts and never broadcast in that direction again. This solves the problem of routers determining where the hosts actually are. Distances to hosts will be subsequently determined by the propagation time of the last packet from the host to its adjacent router. All packets other than RoutingUpdatePackets will be dropped during this dynamic initialization phase.

Open questions:
1) How does a router choose a "default link"?
2) Is there a better way to trigger dynamic routing than on regular time intervals?
3) If dynamic routing does not take place on regular time intervals, how will a router know when it has received all the proper distance estimates?

**Comment by kexinrong** [comment]
"Link weights will be the propagation time of the RoutingUpdatePackets"
Just to be clear, link weights should be link delay + RoutingUpdatePackets.size / link_rate

**Comment by kexinrong** [comment]
Questions:
2,3: regular interval is fine
1: if we have static, the default link can just be taken from that table. otherwise i'm not sure

**Comment by adbh94** [comment]
@kexinrong Yes, link weight will be transmission plus propagation delay: env.now - packet.get_timestamp(). Perhaps we don't need a "default link"? When dynamic routing is over, each router should have a distance estimate to all hosts, so there should never be a need to default to a link.

**Comment by sdhpzhtk** [comment]
From my understanding of dynamic routing, each node should send out the RoutingUpdatePacket to its neighbors, then this will INCLUDE hosts as well. Therefore, hosts should also send out RoutingUpdatePacket to its neighbors (with the cost all other nodes as infinity, and to its own as 0). @adbh94

**Comment by adbh94** [comment]
@sdhpzhtk How about hosts only have to respond to RoutingUpdatePackets? They will send a singleton distance vector saying that the cost to themselves is 0. That way, hosts don't need to be programmed to start dynamic routing, only respond to it.

So a router concludes dynamic routing 1s after it starts it? Because our link weights are the propagation delays, the time it will take to complete dynamic routing is the delay over the longest shortest path between two devices.

Another question: should routers simply ignore RoutingUpdatePackets that arrive not during the interval [t, t+1], where t is a multiple of the routing update period (e.g., 5s)?
