### ISSUE TITLE
Packet class unit test error

### ISSUE THREAD

**Issue by kexinrong** [kexinrong/NetworkSimulator#8]
I got the following messages when trying to run packet_test.py:

Traceback (most recent call last):
  File "test_packet.py", line 4, in <module>
    class PacketTest(unittest.TestCase):
  File "test_packet.py", line 12, in PacketTest
    PACKET_TYPE = Packet.PacketTypes.data_packet
AttributeError: 'Enum' object has no attribute 'data_packet'

Anyone else run into the same problem?

**Comment by adbh94** [comment]
The Enum class was introduced in Python 3.4, so you're likely getting an error because you are using Python 2.7.
